MSR_View_Login/Models/MapModalViewModel.cs
using MSR_Web_App.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MSR_Web_App.Models
{
    public class MapModalViewModel
    {
        public Section Section { get; set; }

    }
}

MSR_View_Login/Controllers/UserVeteranController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MSR_Web_App.Models;
using Microsoft.AspNet.Identity;
using System.IO;

namespace MSR_Web_App.Controllers
{
    [Authorize]
    public class UserVeteranController : Controller
    {
        private Msr_Database_Release_TwoEntities db = new Msr_Database_Release_TwoEntities();
        PortfolioCreateViewModel viewModel = new PortfolioCreateViewModel();

        // GET: Veteran
        public ActionResult PortfolioCreation()
        {
            int userID = Convert.ToInt32(User.Identity.GetUserName());
            // Get veteran from login info 
            viewModel.Veteran = db.Veterans.SingleOrDefault(v => v.Id == userID);
            viewModel.Sections = db.Sections.Where(s => s.Veteran.Id ==userID).ToList();

            return View("PortfolioCreation", viewModel);
        }
        
        [HttpPost]
        public ActionResult EditSectionMap(Section section)
        {
            Section sectionToUpdate = db.Sections.SingleOrDefault(s => s.Id == section.Id && s.Veteran_Id == section.Veteran_Id);

            sectionToUpdate.CoordX = section.CoordX;
            sectionToUpdate.CoordY = section.CoordY;
            sectionToUpdate.CameraZoom = section.CameraZoom;

            try
            {
                db.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

            return RedirectToAction("PortfolioCreation", viewModel);
        }

        public ActionResult _MapModal(Section section)
        {
            return PartialView(section);
        }

        public ActionResult EditProfilePicture(Veteran veteran)
        {
            Veteran veteranToUpdate = db.Veterans.Single(v => v.Id == veteran.Id);

            veteranToUpdate.ProfilePicture = veteran.ProfilePicture;

            try
            {
                db.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

            return RedirectToAction("PortfolioCreation", viewModel);
        }

        public ActionResult EditSection(Content content, Section section, string editSection)
        {
            
            // get ALL current sections
            viewModel.Sections = db.Sections.ToList();

            if (editSection == "AddContent")
            {
                // get current sections
                viewModel.Sections = db.Sections.ToList();
                int vetId = Int32.Parse(User.Identity.GetUserName());
                Veteran veteran = db.Veterans.SingleOrDefault(v => v.Id == vetId);
                Section currentSection = db.Sections.FirstOrDefault(s => s.Id == content.Section_Id);
                //content.FK_Section_Id = currentSection.Id;
                content.Section = currentSection;

                content.Section.Veteran = veteran;

                // find next Id for section (largest)
                int nextId = 0;
                foreach (Content c in currentSection.Contents)
                {
                    if (c.Id > nextId)
                    {
                        nextId = c.Id;
                    }

                }

                content.Id = nextId + 1;

                content.Veteran_Id = Int32.Parse(User.Identity.GetUserName());

                db.Contents.Add(content);
                try
                {
                    db.SaveChanges();
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
                {
                    Exception raise = dbEx;
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string message = string.Format("{0}:{1}",
                                validationErrors.Entry.Entity.ToString(),
                                validationError.ErrorMessage);
                            // raise a new exception nesting
                            // the current instance as InnerException
                            raise = new InvalidOperationException(message, raise);
                        }
                    }
                    throw raise;
                }
                
            }
            else if (editSection == "Delete")
            {
                // Delete contents for section first
                foreach (Content c in db.Contents)
                {
                    if (c.Section_Id == section.Id && section.Veteran_Id == c.Veteran_Id)
                    {
                        db.Contents.Remove(c);
                    }
                }

                // Delete section
                Section sectionToDelete = db.Sections.SingleOrDefault(s => s.Id == section.Id && s.Veteran_Id == section.Veteran_Id);
                db.Sections.Remove(sectionToDelete);
            }

            try
            {
                db.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

            return RedirectToAction("PortfolioCreation", viewModel);
        }

        public ActionResult AddSection(Section section)
        {
            int veteranId = Convert.ToInt32(User.Identity.GetUserName());

            viewModel.Sections = db.Sections.Where(s => s.Veteran_Id == veteranId).ToList();

            // find next Id for section (largest)
            
            int nextId = 0;

            if (viewModel.Sections.Count == 0)
            {
                section.Id = 1;
            }
            else
            {
                foreach (Section s in viewModel.Sections)
                {
                    if (s.Id > nextId)
                    {
                        nextId = s.Id;
                    }
                    section.Id = nextId + 1;
                }
            }

            db.Sections.Add(section);

            try
            {
                db.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

            return RedirectToAction("PortfolioCreation", viewModel);
        }

        public ActionResult EditContent(Content content, string editContent)
        {

            content.Veteran_Id = Int32.Parse(User.Identity.GetUserName());

            if (editContent == "Save")
            {
                Content contentToSave = db.Contents.Single(c => c.Id == content.Id && c.Section_Id == content.Section_Id && c.Veteran_Id == content.Veteran_Id);
                contentToSave.Title = content.Title;
                contentToSave.Timestamp = content.Timestamp;
                contentToSave.MediaType = content.MediaType;
                contentToSave.Media = content.Media;
                contentToSave.Source = content.Source;
                contentToSave.DisplayPosition = content.DisplayPosition;
            }

MSR_View_Login/Views/Shared/_ImageModal.cshtml
<!--Modal Image View-->
<div class="modal fade" id="enlargeImageModal" tabindex="-1" role="dialog" aria-labelledby="enlargeImageModal" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
            </div>
            <div class="modal-body row justify-content-md-center">
                <img src="" class="col enlargeImageModalSource" style="flex-grow:initial;">
            </div>
        </div>
    </div>
</div>
<!--./Modal Image View-->

<script>
    $(function () {
        $(".img-click").on('click', function () {

            $('.enlargeImageModalSource').attr('src', $(this).attr('src'));
            $('#enlargeImageModal').modal('show');
        });
    });
</script>

MSR_View_Login/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/ico" href="https://image.ibb.co/cU4Ki0/MSR-Star-Logo.png">
    <title>@ViewBag.Title</title>

    <!--Styles-->
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/Content/custom.css">
    <link rel="stylesheet" href="https://unpkg.com/simplebar@latest/dist/simplebar.css" />
    <!--./Styles-->
    <!--Scripts-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>
    <script src="~/Scripts/script.js"></script>

    <!--./Scripts-->
    <!--Map Resources-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
          integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
          crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
            integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
            crossorigin=""></script>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.49.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.49.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />
    <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
    <!--./Map Resources-->
</head>
<body>
    <header>
        <!--Navbar-->
        <nav class="navbar overwrite-navbar-text overwrite-bg-navbar navbar-expand-lg fixed-top">
            <img src="https://image.ibb.co/cU4Ki0/MSR-Star-Logo.png" class="navbar-brand" id="msrlogo" alt="MSR Logo" height="45" width="45">
            <a href="/" class="navbar-brand align-self-center"><strong>My School Remembers</strong></a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="custom-navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="navbar-item">
                        <a href="/" class="nav-link">Home</a>
                    </li>
                    <li class="navbar-item">
                        <a href="/veterans" class="nav-link">Veterans</a>
                    </li>
                    <li class="navbar-item">
                        <a href="https://www.myschoolremembers.org/email-enquiry" class="nav-link">Contact</a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    </header>
    <!--./NavBar-->
    <div>
        <!--Content-->
        @RenderBody()
        <!--./Content-->
        <!--Footer/Copyright-->
        <footer class="custom-footer">
            <div class="footer-row">
                <p class="col-sm-12 text-left">&copy; 2019 My School Remembers</p>
            </div>
        </footer>
        <!--./Footer/Copyright-->
    </div>
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

</body>
</html>

MSR_View_Login/Views/Shared/_Map.cshtml
<div>
    <script>
        var map = L.map('leaflet-map').setView([-26.588527, 134.291215], 3);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox.streets',
            accessToken: 'pk.eyJ1IjoibWljaDkzIiwiYSI6ImNqZXMyMHMzeDAya3QzM3BlcWZoN3kyOHIifQ.o-Pj-zET7xQeBp7mOEt7Og'
        }).addTo(map);

        //mark geocode by default adds a marker on the search result
        L.Control.geocoder({
            defaultMarkGeocode: false
        })
            .on('markgeocode', function (e) {
                var bbox = e.geocode.bbox;
                var poly = L.polygon([
                    bbox.getSouthEast(),
                    bbox.getNorthEast(),
                    bbox.getNorthWest(),
                    bbox.getSouthWest()
                ]);
                map.fitBounds(poly.getBounds());
            })
            .addTo(map);

        var zoomLevel = map._zoom;
        var marker = L.marker();

        function onMapClick(e) {
            map.removeLayer(marker);
            marker = L.marker(e.latlng).addTo(map);
            $('#txtCoordX').val(e.latlng.lat);
            $('#txtCoordY').val(e.latlng.lng);
        }
        function updateZoom(e) {
            $('#txtCameraZoom').val(map._zoom);
        }

        // this fixes the issue with greyed out tiles displaying until resize
        $('#mapModal').on('shown.bs.modal', function (e) {
            jQuery.noConflict();
            setTimeout(function () { map.invalidateSize(); }, 10);
        });

    </script>
</div>

MSR_View_Login/Views/Shared/_MapModal.cshtml
@model MSR_Web_App.Models.Section


<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="myModal-label">Edit Event Map</h4>
        </div>
        <div class="modal-body">
            <div class="col-sm-9 leaflet-map" id="leaflet-map">
                @{Html.RenderPartial("_Map");}
            </div>
            <div class="col-sm-3 map-modal-input-group">
                @using (Html.BeginForm("EditSectionMap", "UserVeteran", FormMethod.Post, new { id = "mapForm" }))
                {
                    <div class="form-group">
                        @Html.TextBoxFor(model => model.Id)
                        @Html.TextBoxFor(model => model.Veteran_Id)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CoordX)
                        @Html.TextBoxFor(model => model.CoordX, new { Id = "txtCoordX"})
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CoordY)
                        @Html.TextBoxFor(model => model.CoordY, new { Id = "txtCoordY" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CameraZoom)
                        @Html.TextBoxFor(model => model.CameraZoom, new { Id = "txtCameraZoom" })
                    </div>

                        @*<label>@Html.RadioButton("rdbStreet", "Street") Street</label>
               	 <label>@Html.RadioButton("rdbSuburb", "Suburb") Suburb</label>
               	 <label>@Html.RadioButton("rdbCity", "City") City</label>
               	 <label>@Html.RadioButton("rdbState", "State") State</label>
               	 <label>@Html.RadioButton("rdbCountry", "Country") Country</label>
               	 <label>@Html.RadioButton("rdbCustom", "Custom") Custom</label>*@
             }
                    </div>
               	 </div>
	 <div class="modal-footer">
        	 <button class="btn btn-primary" id="btnSave" type="button" onclick="$('#mapForm').submit();">Save</button>
            <button class="btn btn-default" data-dismiss="modal" id="btnCancel">Cancel</button>
        </div>
    </div>
</div>

MSR_View_Login/Views/Shared/_PortfolioMap.cshtml
<!--Map Script-->
<script>
            mapboxgl.accessToken = 'pk.eyJ1IjoiMTAxNjE0ODU1IiwiYSI6ImNqbWZ2Zzh4cjBjZGszdnF5dzdwdnRmMDUifQ.1Y24aVGqUdqGM2i7_6wHvw';
            var map = new mapboxgl.Map({
                container: 'map',
                style: 'mapbox://styles/mapbox/light-v9',
                center: [-96, 37.8],
                zoom: 3
            });
</script>
<!--Map Script-->